name:                netherrack
version:             0.1.0.0
github:              "githubuser/netherrack"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

default-extensions:
    - TypeApplications
    - OverloadedStrings
    - LambdaCase
    - RecordWildCards
    - DeriveGeneric
    - DeriveAnyClass

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/netherrack#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- fsnotify
- bytestring
- binary
- network
- network-run
- safe-exceptions
- config-ini
- transformers
- text
- discord-haskell
- unliftio
- aeson
- http-conduit
- lens
- emojis

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src
    # - src/log

executables:
  netherrack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netherrack

tests:
  netherrack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netherrack
